### DISCUSSION TITLE
【Vue3 - 3.2.13】踩坑系列

### DISCUSSION THREAD

**Discussion by swlws** [swustzzh/coder_books#23] [Q&A]
Q1：样式穿透问题

A1：通过`:deep`实现样式穿透的前置条件，`<template></template>`必须有一个根节点；`:deep`写在最外层，示例：
```scss
:deep(.el-input){
  .el_iinput_warpper{
       border-color: red
   }
}
```
